import type { RentalStore } from './types';
import { buildVisualTemplateHtml, defaultVisualTemplateConfig } from './services/template-visual-builder';

function seedVisualTemplate(code: string, type: 'CONFIRMACION_RESERVA' | 'PRESUPUESTO' | 'FACTURA', lang: string, title: string, now: string) {
  const cfg = defaultVisualTemplateConfig(type, lang);
  return {
    id: `tpl-${code.toLowerCase()}`,
    templateCode: code,
    templateType: type,
    language: lang,
    title,
    templateFunction: type,
    htmlContent: buildVisualTemplateHtml(type, lang, cfg, {}),
    active: true,
    createdAt: now,
    updatedAt: now,
  };
}

export function createSeedStore(): RentalStore {
  const NOW = new Date().toISOString();

  const today = new Date();
  const d = (n: number): string => {
    const dt = new Date(today);
    dt.setDate(dt.getDate() + n);
    return dt.toISOString().split('T')[0];
  };
  const yr = today.getFullYear();
  const rsv = (n: number) => `RSV-${yr}-${String(n).padStart(6, '0')}`;

  return {
    meta: {
      version: '3.0.0',
      lastUpdated: NOW,
    },
    settings: {
      name: 'RentIQ Demo S.L.',
      nif: 'B12345678',
      address: 'Calle Mayor 1, 28001 Madrid',
      phone: '+34 91 000 0000',
      email: 'info@rentiq.local',
      defaultBranchId: 'branch-1',
      invoiceSeries: 'F',
      ivaPercent: 21,
      deliveryLocations: [],
      overlapMinHours: 2,
    },
    branches: [
      {
        id: 'branch-1',
        name: 'Sucursal Principal',
        address: 'Calle Mayor 1, 28001 Madrid',
        phone: '+34 91 000 0000',
        email: 'madrid@rentiq.local',
        active: true,
        contractPrefix: 'MAD',
        contractCounter: 0,
        invoiceCounter: 0,
        schedule: {
          mon: { open: '08:00', close: '20:00' },
          tue: { open: '08:00', close: '20:00' },
          wed: { open: '08:00', close: '20:00' },
          thu: { open: '08:00', close: '20:00' },
          fri: { open: '08:00', close: '20:00' },
          sat: { open: '09:00', close: '14:00' },
          exceptions: [],
        },
        createdAt: NOW,
      },
    ],
    users: [
      {
        id: 'user-superadmin',
        name: 'Super Admin',
        email: 'superadmin@rentiq.local',
        role: 'SUPER_ADMIN',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'user-admin',
        name: 'Administrador',
        email: 'admin@rentiq.local',
        role: 'ADMIN',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'user-lector',
        name: 'Lector',
        email: 'lector@rentiq.local',
        role: 'LECTOR',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    clients: [
      {
        id: 'client-1',
        type: 'PARTICULAR' as const,
        name: 'Juan',
        surname: 'García López',
        email: 'juan@example.com',
        phone: '+34 600 000 001',
        nif: '12345678A',
        address: 'Calle Sol 5, Madrid',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
        notes: '',
      },
      {
        id: 'client-2',
        type: 'EMPRESA' as const,
        name: 'Contacto',
        surname: 'Viajes',
        companyName: 'Empresa Viajes S.L.',
        email: 'info@viajes.com',
        phone: '+34 600 000 002',
        nif: 'B87654321',
        address: 'Avenida Luna 10, Madrid',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
        notes: '',
      },
      {
        id: 'client-3',
        type: 'PARTICULAR' as const,
        name: 'Carlos',
        surname: 'Martínez Díaz',
        email: 'carlos@example.com',
        phone: '+34 600 000 003',
        nif: '87654321B',
        address: 'Calle Luna 12, Madrid',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
        notes: '',
      },
      {
        id: 'client-4',
        type: 'PARTICULAR' as const,
        name: 'Ana',
        surname: 'Ruiz Fernández',
        email: 'ana@example.com',
        phone: '+34 600 000 004',
        nif: '11223344C',
        address: 'Calle Mayor 20, Madrid',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
        notes: '',
      },
      {
        id: 'client-5',
        type: 'EMPRESA' as const,
        name: 'Responsable',
        surname: 'Flota',
        companyName: 'Logística Express S.A.',
        email: 'flota@logistica.com',
        phone: '+34 600 000 005',
        nif: 'A11223344',
        address: 'Polígono Norte 45, Madrid',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
        notes: '',
      },
    ],
    vehicleCategories: [
      {
        id: 'cat-mini',
        code: 'A',
        name: 'MINI',
        description: 'Vehículos urbanos compactos',
        active: true,
        createdAt: NOW,
      },
      {
        id: 'cat-compacto',
        code: 'B',
        name: 'COMPACTO',
        description: 'Vehículos compactos medianos',
        active: true,
        createdAt: NOW,
      },
      {
        id: 'cat-suv',
        code: 'C',
        name: 'SUV',
        description: 'Vehículos SUV y todoterreno',
        active: true,
        createdAt: NOW,
      },
    ],
    vehicleModels: [
      {
        id: 'model-1',
        brand: 'Toyota',
        model: 'Aygo',
        categoryId: 'cat-mini',
        transmission: 'MANUAL',
        fuel: 'GASOLINA',
        seats: 5,
        features: ['Aire acondicionado', 'Radio'],
        active: true,
        createdAt: NOW,
      },
      {
        id: 'model-2',
        brand: 'Volkswagen',
        model: 'Golf',
        categoryId: 'cat-compacto',
        transmission: 'MANUAL',
        fuel: 'GASOLINA',
        seats: 5,
        features: ['Aire acondicionado', 'GPS', 'Bluetooth'],
        active: true,
        createdAt: NOW,
      },
      {
        id: 'model-3',
        brand: 'Toyota',
        model: 'RAV4',
        categoryId: 'cat-suv',
        transmission: 'AUTOMATICO',
        fuel: 'HIBRIDO',
        seats: 5,
        features: ['Aire acondicionado', 'GPS', 'Bluetooth', 'Cámara trasera'],
        active: true,
        createdAt: NOW,
      },
    ],
    vehicles: [
      {
        id: 'vehicle-1',
        plate: '1234ABC',
        modelId: 'model-1',
        categoryId: 'cat-mini',
        branchId: 'branch-1',
        year: 2022,
        color: 'Blanco',
        owner: 'PROPIO',
        currentOdometer: 15000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-2',
        plate: '5678DEF',
        modelId: 'model-2',
        categoryId: 'cat-compacto',
        branchId: 'branch-1',
        year: 2023,
        color: 'Gris',
        owner: 'PROPIO',
        currentOdometer: 8500,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-3',
        plate: '9012GHI',
        modelId: 'model-3',
        categoryId: 'cat-suv',
        branchId: 'branch-1',
        year: 2023,
        color: 'Negro',
        owner: 'RENTING',
        currentOdometer: 22000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-4',
        plate: '3456JKL',
        modelId: 'model-1',
        categoryId: 'cat-mini',
        branchId: 'branch-1',
        year: 2021,
        color: 'Rojo',
        owner: 'PROPIO',
        currentOdometer: 31000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-5',
        plate: '7890MNO',
        modelId: 'model-2',
        categoryId: 'cat-compacto',
        branchId: 'branch-1',
        year: 2022,
        color: 'Blanco',
        owner: 'PROPIO',
        currentOdometer: 12000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-6',
        plate: '2345PQR',
        modelId: 'model-3',
        categoryId: 'cat-suv',
        branchId: 'branch-1',
        year: 2024,
        color: 'Plata',
        owner: 'RENTING',
        currentOdometer: 5500,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    vehicleExtras: [
      {
        id: 'extra-1',
        code: 'SEGURO_BASICO',
        name: 'Seguro Básico',
        pricingMode: 'PER_DAY',
        unitPrice: 8,
        active: true,
        createdAt: NOW,
      },
      {
        id: 'extra-2',
        code: 'CDW',
        name: 'CDW (Colisión sin franquicia)',
        pricingMode: 'PER_DAY',
        unitPrice: 15,
        active: true,
        createdAt: NOW,
      },
    ],
    vehicleInsurances: [],
    vehicleTasks: [],
    reservations: [
      {
        id: 'rsv-1', number: rsv(1), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-1', categoryId: 'cat-mini', assignedPlate: '1234ABC',
        startDate: d(-3), startTime: '09:00', endDate: d(2), endTime: '18:00',
        billedDays: 6, basePrice: 180, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 180,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-2', number: rsv(2), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Aeropuerto',
        clientId: 'client-2', categoryId: 'cat-mini', assignedPlate: '1234ABC',
        startDate: d(4), startTime: '10:00', endDate: d(8), endTime: '17:00',
        billedDays: 5, basePrice: 150, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 150,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-3', number: rsv(3), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-1', categoryId: 'cat-compacto', assignedPlate: '5678DEF',
        startDate: d(-1), startTime: '09:00', endDate: d(5), endTime: '18:00',
        billedDays: 7, basePrice: 280, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 280,
        extras: [],
        status: 'CONFIRMADA' as const, contractId: 'ctr-1', notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-4', number: rsv(4), branchId: 'branch-1',
        pickupLocation: 'Puerto', returnLocation: 'Puerto',
        clientId: 'client-2', categoryId: 'cat-compacto', assignedPlate: '5678DEF',
        startDate: d(6), startTime: '08:00', endDate: d(11), endTime: '18:00',
        billedDays: 6, basePrice: 240, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 240,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-5', number: rsv(5), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Aeropuerto',
        clientId: 'client-2', categoryId: 'cat-suv', assignedPlate: '9012GHI',
        startDate: d(3), startTime: '09:00', endDate: d(9), endTime: '17:00',
        billedDays: 7, basePrice: 406, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 406,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-6', number: rsv(6), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Oficina Principal',
        clientId: 'client-1', categoryId: 'cat-suv', assignedPlate: '9012GHI',
        startDate: d(15), startTime: '10:00', endDate: d(19), endTime: '18:00',
        billedDays: 5, basePrice: 290, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 290,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      // rsv-7 y rsv-8: huérfanas (sin matrícula asignada)
      {
        id: 'rsv-7', number: rsv(7), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-2', categoryId: 'cat-compacto',
        startDate: d(2), startTime: '09:00', endDate: d(7), endTime: '18:00',
        billedDays: 6, basePrice: 240, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 240,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-8', number: rsv(8), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Aeropuerto',
        clientId: 'client-1', categoryId: 'cat-mini',
        startDate: d(10), startTime: '11:00', endDate: d(14), endTime: '17:00',
        billedDays: 5, basePrice: 125, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 125,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      // ── 3456JKL (MINI) — 3 reservas consecutivas, las dos últimas con solape ──
      {
        id: 'rsv-9', number: rsv(9), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-3', categoryId: 'cat-mini', assignedPlate: '3456JKL',
        startDate: d(-2), startTime: '09:00', endDate: d(3), endTime: '18:00',
        billedDays: 6, basePrice: 150, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 150,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        // Empieza el día siguiente de rsv-9 → solape detectado
        id: 'rsv-10', number: rsv(10), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Aeropuerto',
        clientId: 'client-4', categoryId: 'cat-mini', assignedPlate: '3456JKL',
        startDate: d(4), startTime: '08:00', endDate: d(9), endTime: '17:00',
        billedDays: 6, basePrice: 180, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 180,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        // Empieza el día siguiente de rsv-10 → también solape
        id: 'rsv-11', number: rsv(11), branchId: 'branch-1',
        pickupLocation: 'Puerto', returnLocation: 'Puerto',
        clientId: 'client-5', categoryId: 'cat-mini', assignedPlate: '3456JKL',
        startDate: d(10), startTime: '09:00', endDate: d(16), endTime: '18:00',
        billedDays: 7, basePrice: 175, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 175,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      // ── 7890MNO (COMPACTO) — contratada + hueco + confirmada + petición ──
      {
        id: 'rsv-12', number: rsv(12), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-5', categoryId: 'cat-compacto', assignedPlate: '7890MNO',
        startDate: d(-4), startTime: '09:00', endDate: d(2), endTime: '18:00',
        billedDays: 7, basePrice: 280, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 280,
        extras: [],
        status: 'CONFIRMADA' as const, contractId: 'ctr-2', notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-13', number: rsv(13), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Oficina Principal',
        clientId: 'client-3', categoryId: 'cat-compacto', assignedPlate: '7890MNO',
        startDate: d(8), startTime: '10:00', endDate: d(14), endTime: '17:00',
        billedDays: 7, basePrice: 245, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 245,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-14', number: rsv(14), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-4', categoryId: 'cat-compacto', assignedPlate: '7890MNO',
        startDate: d(20), startTime: '09:00', endDate: d(27), endTime: '18:00',
        billedDays: 8, basePrice: 280, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 280,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      // ── 2345PQR (SUV) — reserva larga contratada + petición ──
      {
        id: 'rsv-15', number: rsv(15), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Aeropuerto',
        clientId: 'client-5', categoryId: 'cat-suv', assignedPlate: '2345PQR',
        startDate: d(-1), startTime: '08:00', endDate: d(12), endTime: '18:00',
        billedDays: 14, basePrice: 700, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 700,
        extras: [],
        status: 'CONFIRMADA' as const, contractId: 'ctr-3', notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-16', number: rsv(16), branchId: 'branch-1',
        pickupLocation: 'Puerto', returnLocation: 'Puerto',
        clientId: 'client-1', categoryId: 'cat-suv', assignedPlate: '2345PQR',
        startDate: d(18), startTime: '09:00', endDate: d(24), endTime: '18:00',
        billedDays: 7, basePrice: 406, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 406,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      // ── Huérfanas adicionales ──
      {
        id: 'rsv-17', number: rsv(17), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Aeropuerto',
        clientId: 'client-3', categoryId: 'cat-suv',
        startDate: d(5), startTime: '09:00', endDate: d(11), endTime: '17:00',
        billedDays: 7, basePrice: 406, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 406,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-18', number: rsv(18), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-4', categoryId: 'cat-mini',
        startDate: d(-1), startTime: '11:00', endDate: d(4), endTime: '17:00',
        billedDays: 6, basePrice: 150, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 150,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
    ],
    contracts: [
      {
        id: 'ctr-1',
        number: 'MAD-2026-000001',
        reservationId: 'rsv-3',
        branchId: 'branch-1',
        clientId: 'client-1',
        plate: '5678DEF',
        categoryId: 'cat-compacto',
        pickupLocation: 'Oficina Principal',
        returnLocation: 'Oficina Principal',
        startDate: d(-1), startTime: '09:00',
        endDate: d(5), endTime: '18:00',
        billedDays: 7,
        basePrice: 280,
        extrasTotal: 0, insuranceTotal: 0, fuelCharge: 0,
        penalties: 0, discount: 0, total: 280,
        extras: [],
        status: 'ABIERTO' as const,
        payments: [],
        internalExpenseIds: [],
        auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'ctr-2',
        number: 'MAD-2026-000002',
        reservationId: 'rsv-12',
        branchId: 'branch-1',
        clientId: 'client-5',
        plate: '7890MNO',
        categoryId: 'cat-compacto',
        pickupLocation: 'Oficina Principal',
        returnLocation: 'Oficina Principal',
        startDate: d(-4), startTime: '09:00',
        endDate: d(2), endTime: '18:00',
        billedDays: 7,
        basePrice: 280,
        extrasTotal: 0, insuranceTotal: 0, fuelCharge: 0,
        penalties: 0, discount: 0, total: 280,
        extras: [],
        status: 'ABIERTO' as const,
        payments: [],
        internalExpenseIds: [],
        auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'ctr-3',
        number: 'MAD-2026-000003',
        reservationId: 'rsv-15',
        branchId: 'branch-1',
        clientId: 'client-5',
        plate: '2345PQR',
        categoryId: 'cat-suv',
        pickupLocation: 'Aeropuerto',
        returnLocation: 'Aeropuerto',
        startDate: d(-1), startTime: '08:00',
        endDate: d(12), endTime: '18:00',
        billedDays: 14,
        basePrice: 700,
        extrasTotal: 0, insuranceTotal: 0, fuelCharge: 0,
        penalties: 0, discount: 0, total: 700,
        extras: [],
        status: 'ABIERTO' as const,
        payments: [],
        internalExpenseIds: [],
        auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
    ],
    invoices: [],
    tariffPlans: [
      {
        id: 'tariff-1',
        name: 'Tarifa Estándar 2026',
        code: 'EST-26',
        validFrom: '2026-01-01',
        validTo: '2026-12-31',
        active: true,
        createdAt: NOW,
      },
    ],
    tariffBrackets: [
      {
        id: 'bracket-1',
        planId: 'tariff-1',
        label: '1-3 días',
        minDays: 1,
        maxDays: 3,
        order: 1,
      },
      {
        id: 'bracket-2',
        planId: 'tariff-1',
        label: '4-7 días',
        minDays: 4,
        maxDays: 7,
        order: 2,
      },
      {
        id: 'bracket-3',
        planId: 'tariff-1',
        label: '8+ días',
        minDays: 8,
        maxDays: null,
        order: 3,
      },
    ],
    tariffPrices: [
      // bracket-1
      { id: 'tp-1', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-mini',     pricingType: 'DIA' as const, price: 35 },
      { id: 'tp-2', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-compacto', pricingType: 'DIA' as const, price: 45 },
      { id: 'tp-3', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-suv',      pricingType: 'DIA' as const, price: 65 },
      // bracket-2
      { id: 'tp-4', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-mini',     pricingType: 'DIA' as const, price: 30 },
      { id: 'tp-5', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-compacto', pricingType: 'DIA' as const, price: 40 },
      { id: 'tp-6', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-suv',      pricingType: 'DIA' as const, price: 58 },
      // bracket-3
      { id: 'tp-7', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-mini',     pricingType: 'DIA' as const, price: 25 },
      { id: 'tp-8', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-compacto', pricingType: 'DIA' as const, price: 35 },
      { id: 'tp-9', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-suv',      pricingType: 'DIA' as const, price: 50 },
    ],
    expenses: [],
    salesChannels: [
      {
        id: 'channel-1',
        name: 'Directo',
        code: 'DIR',
        commissionPercent: 0,
        active: true,
        createdAt: NOW,
      },
      {
        id: 'channel-2',
        name: 'Online',
        code: 'ONL',
        commissionPercent: 10,
        active: true,
        createdAt: NOW,
      },
    ],
    templates: [
      seedVisualTemplate('CONF_RES_ES_BASE', 'CONFIRMACION_RESERVA', 'es', 'Confirmación de reserva (ES)', NOW),
      seedVisualTemplate('CONF_RES_EN_BASE', 'CONFIRMACION_RESERVA', 'en', 'Reservation confirmation (EN)', NOW),
      seedVisualTemplate('PRES_BASE_ES',     'PRESUPUESTO',          'es', 'Presupuesto (ES)',             NOW),
      seedVisualTemplate('PRES_BASE_EN',     'PRESUPUESTO',          'en', 'Quotation (EN)',               NOW),
      seedVisualTemplate('FAC_BASE_ES',      'FACTURA',              'es', 'Factura (ES)',                 NOW),
      seedVisualTemplate('FAC_BASE_EN',      'FACTURA',              'en', 'Invoice (EN)',                 NOW),
    ],
    vehicleBlocks: [
      {
        id: 'block-1',
        plate: '9012GHI',
        startDate: d(11),
        endDate: d(13),
        reason: 'ITV',
        createdBy: 'user-admin',
        createdAt: NOW,
      },
      {
        id: 'block-2',
        plate: '1234ABC',
        startDate: d(18),
        endDate: d(20),
        reason: 'Revisión taller',
        createdBy: 'user-admin',
        createdAt: NOW,
      },
      {
        id: 'block-3',
        plate: '3456JKL',
        startDate: d(22),
        endDate: d(23),
        reason: 'Limpieza interior',
        createdBy: 'user-admin',
        createdAt: NOW,
      },
    ],
    promoCodes: [],
  };
}
