import type { RentalStore } from './types';

export function createSeedStore(): RentalStore {
  const NOW = new Date().toISOString();
  return {
    meta: {
      version: '3.0.0',
      lastUpdated: NOW,
    },
    settings: {
      name: 'RentIQ Demo S.L.',
      nif: 'B12345678',
      address: 'Calle Mayor 1, 28001 Madrid',
      phone: '+34 91 000 0000',
      email: 'info@rentiq.local',
      defaultBranchId: 'branch-1',
      invoiceSeries: 'F',
      ivaPercent: 21,
    },
    branches: [
      {
        id: 'branch-1',
        name: 'Sucursal Principal',
        address: 'Calle Mayor 1, 28001 Madrid',
        phone: '+34 91 000 0000',
        email: 'madrid@rentiq.local',
        active: true,
        contractPrefix: 'MAD',
        contractCounter: 0,
        invoiceCounter: 0,
        schedule: {
          mon: { open: '08:00', close: '20:00' },
          tue: { open: '08:00', close: '20:00' },
          wed: { open: '08:00', close: '20:00' },
          thu: { open: '08:00', close: '20:00' },
          fri: { open: '08:00', close: '20:00' },
          sat: { open: '09:00', close: '14:00' },
          exceptions: [],
        },
        createdAt: NOW,
      },
    ],
    users: [
      {
        id: 'user-superadmin',
        name: 'Super Admin',
        email: 'superadmin@rentiq.local',
        role: 'SUPER_ADMIN',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'user-admin',
        name: 'Administrador',
        email: 'admin@rentiq.local',
        role: 'ADMIN',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'user-lector',
        name: 'Lector',
        email: 'lector@rentiq.local',
        role: 'LECTOR',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    clients: [],
    vehicleCategories: [
      {
        id: 'cat-mini',
        code: 'A',
        name: 'MINI',
        description: 'Vehículos urbanos compactos',
        active: true,
        createdAt: NOW,
      },
      {
        id: 'cat-compacto',
        code: 'B',
        name: 'COMPACTO',
        description: 'Vehículos compactos medianos',
        active: true,
        createdAt: NOW,
      },
      {
        id: 'cat-suv',
        code: 'C',
        name: 'SUV',
        description: 'Vehículos SUV y todoterreno',
        active: true,
        createdAt: NOW,
      },
    ],
    vehicleModels: [
      {
        id: 'model-1',
        brand: 'Toyota',
        model: 'Aygo',
        categoryId: 'cat-mini',
        transmission: 'MANUAL',
        fuel: 'GASOLINA',
        seats: 5,
        features: ['Aire acondicionado', 'Radio'],
        active: true,
        createdAt: NOW,
      },
      {
        id: 'model-2',
        brand: 'Volkswagen',
        model: 'Golf',
        categoryId: 'cat-compacto',
        transmission: 'MANUAL',
        fuel: 'GASOLINA',
        seats: 5,
        features: ['Aire acondicionado', 'GPS', 'Bluetooth'],
        active: true,
        createdAt: NOW,
      },
      {
        id: 'model-3',
        brand: 'Toyota',
        model: 'RAV4',
        categoryId: 'cat-suv',
        transmission: 'AUTOMATICO',
        fuel: 'HIBRIDO',
        seats: 5,
        features: ['Aire acondicionado', 'GPS', 'Bluetooth', 'Cámara trasera'],
        active: true,
        createdAt: NOW,
      },
    ],
    vehicles: [
      {
        id: 'vehicle-1',
        plate: '1234ABC',
        modelId: 'model-1',
        categoryId: 'cat-mini',
        branchId: 'branch-1',
        year: 2022,
        color: 'Blanco',
        owner: 'PROPIO',
        currentOdometer: 15000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-2',
        plate: '5678DEF',
        modelId: 'model-2',
        categoryId: 'cat-compacto',
        branchId: 'branch-1',
        year: 2023,
        color: 'Gris',
        owner: 'PROPIO',
        currentOdometer: 8500,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-3',
        plate: '9012GHI',
        modelId: 'model-3',
        categoryId: 'cat-suv',
        branchId: 'branch-1',
        year: 2023,
        color: 'Negro',
        owner: 'RENTING',
        currentOdometer: 22000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    vehicleExtras: [
      {
        id: 'extra-1',
        code: 'SEGURO_BASICO',
        name: 'Seguro Básico',
        pricingMode: 'PER_DAY',
        unitPrice: 8,
        active: true,
        createdAt: NOW,
      },
      {
        id: 'extra-2',
        code: 'CDW',
        name: 'CDW (Colisión sin franquicia)',
        pricingMode: 'PER_DAY',
        unitPrice: 15,
        active: true,
        createdAt: NOW,
      },
    ],
    vehicleInsurances: [],
    vehicleTasks: [],
    reservations: [],
    contracts: [],
    invoices: [],
    tariffPlans: [
      {
        id: 'tariff-1',
        name: 'Tarifa Estándar 2026',
        pricingMode: 'PRECIO_A',
        validFrom: '2026-01-01',
        validTo: '2026-12-31',
        active: true,
        createdAt: NOW,
      },
    ],
    tariffBrackets: [
      {
        id: 'bracket-1',
        planId: 'tariff-1',
        label: '1-3 días',
        minDays: 1,
        maxDays: 3,
        order: 1,
      },
      {
        id: 'bracket-2',
        planId: 'tariff-1',
        label: '4-7 días',
        minDays: 4,
        maxDays: 7,
        order: 2,
      },
      {
        id: 'bracket-3',
        planId: 'tariff-1',
        label: '8+ días',
        minDays: 8,
        maxDays: null,
        order: 3,
      },
    ],
    tariffPrices: [
      // bracket-1
      { id: 'tp-1', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-mini', price: 35 },
      { id: 'tp-2', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-compacto', price: 45 },
      { id: 'tp-3', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-suv', price: 65 },
      // bracket-2
      { id: 'tp-4', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-mini', price: 30 },
      { id: 'tp-5', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-compacto', price: 40 },
      { id: 'tp-6', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-suv', price: 58 },
      // bracket-3
      { id: 'tp-7', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-mini', price: 25 },
      { id: 'tp-8', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-compacto', price: 35 },
      { id: 'tp-9', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-suv', price: 50 },
    ],
    expenses: [],
    salesChannels: [
      {
        id: 'channel-1',
        name: 'Directo',
        code: 'DIR',
        commissionPercent: 0,
        active: true,
        createdAt: NOW,
      },
      {
        id: 'channel-2',
        name: 'Online',
        code: 'ONL',
        commissionPercent: 10,
        active: true,
        createdAt: NOW,
      },
    ],
    templates: [],
    vehicleBlocks: [],
  };
}
