import type { RentalStore } from './types';

export function createSeedStore(): RentalStore {
  const NOW = new Date().toISOString();

  const today = new Date();
  const d = (n: number): string => {
    const dt = new Date(today);
    dt.setDate(dt.getDate() + n);
    return dt.toISOString().split('T')[0];
  };
  const yr = today.getFullYear();
  const rsv = (n: number) => `RSV-${yr}-${String(n).padStart(6, '0')}`;

  return {
    meta: {
      version: '3.0.0',
      lastUpdated: NOW,
    },
    settings: {
      name: 'RentIQ Demo S.L.',
      nif: 'B12345678',
      address: 'Calle Mayor 1, 28001 Madrid',
      phone: '+34 91 000 0000',
      email: 'info@rentiq.local',
      defaultBranchId: 'branch-1',
      invoiceSeries: 'F',
      ivaPercent: 21,
      deliveryLocations: [],
      overlapMinHours: 2,
    },
    branches: [
      {
        id: 'branch-1',
        name: 'Sucursal Principal',
        address: 'Calle Mayor 1, 28001 Madrid',
        phone: '+34 91 000 0000',
        email: 'madrid@rentiq.local',
        active: true,
        contractPrefix: 'MAD',
        contractCounter: 0,
        invoiceCounter: 0,
        schedule: {
          mon: { open: '08:00', close: '20:00' },
          tue: { open: '08:00', close: '20:00' },
          wed: { open: '08:00', close: '20:00' },
          thu: { open: '08:00', close: '20:00' },
          fri: { open: '08:00', close: '20:00' },
          sat: { open: '09:00', close: '14:00' },
          exceptions: [],
        },
        createdAt: NOW,
      },
    ],
    users: [
      {
        id: 'user-superadmin',
        name: 'Super Admin',
        email: 'superadmin@rentiq.local',
        role: 'SUPER_ADMIN',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'user-admin',
        name: 'Administrador',
        email: 'admin@rentiq.local',
        role: 'ADMIN',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'user-lector',
        name: 'Lector',
        email: 'lector@rentiq.local',
        role: 'LECTOR',
        passwordHash: '',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    clients: [
      {
        id: 'client-1',
        type: 'PARTICULAR' as const,
        name: 'Juan',
        surname: 'García López',
        email: 'juan@example.com',
        phone: '+34 600 000 001',
        nif: '12345678A',
        address: 'Calle Sol 5, Madrid',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
        notes: '',
      },
      {
        id: 'client-2',
        type: 'EMPRESA' as const,
        name: 'Contacto',
        surname: 'Viajes',
        companyName: 'Empresa Viajes S.L.',
        email: 'info@viajes.com',
        phone: '+34 600 000 002',
        nif: 'B87654321',
        address: 'Avenida Luna 10, Madrid',
        active: true,
        createdAt: NOW,
        updatedAt: NOW,
        notes: '',
      },
    ],
    vehicleCategories: [
      {
        id: 'cat-mini',
        code: 'A',
        name: 'MINI',
        description: 'Vehículos urbanos compactos',
        active: true,
        createdAt: NOW,
      },
      {
        id: 'cat-compacto',
        code: 'B',
        name: 'COMPACTO',
        description: 'Vehículos compactos medianos',
        active: true,
        createdAt: NOW,
      },
      {
        id: 'cat-suv',
        code: 'C',
        name: 'SUV',
        description: 'Vehículos SUV y todoterreno',
        active: true,
        createdAt: NOW,
      },
    ],
    vehicleModels: [
      {
        id: 'model-1',
        brand: 'Toyota',
        model: 'Aygo',
        categoryId: 'cat-mini',
        transmission: 'MANUAL',
        fuel: 'GASOLINA',
        seats: 5,
        features: ['Aire acondicionado', 'Radio'],
        active: true,
        createdAt: NOW,
      },
      {
        id: 'model-2',
        brand: 'Volkswagen',
        model: 'Golf',
        categoryId: 'cat-compacto',
        transmission: 'MANUAL',
        fuel: 'GASOLINA',
        seats: 5,
        features: ['Aire acondicionado', 'GPS', 'Bluetooth'],
        active: true,
        createdAt: NOW,
      },
      {
        id: 'model-3',
        brand: 'Toyota',
        model: 'RAV4',
        categoryId: 'cat-suv',
        transmission: 'AUTOMATICO',
        fuel: 'HIBRIDO',
        seats: 5,
        features: ['Aire acondicionado', 'GPS', 'Bluetooth', 'Cámara trasera'],
        active: true,
        createdAt: NOW,
      },
    ],
    vehicles: [
      {
        id: 'vehicle-1',
        plate: '1234ABC',
        modelId: 'model-1',
        categoryId: 'cat-mini',
        branchId: 'branch-1',
        year: 2022,
        color: 'Blanco',
        owner: 'PROPIO',
        currentOdometer: 15000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-2',
        plate: '5678DEF',
        modelId: 'model-2',
        categoryId: 'cat-compacto',
        branchId: 'branch-1',
        year: 2023,
        color: 'Gris',
        owner: 'PROPIO',
        currentOdometer: 8500,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'vehicle-3',
        plate: '9012GHI',
        modelId: 'model-3',
        categoryId: 'cat-suv',
        branchId: 'branch-1',
        year: 2023,
        color: 'Negro',
        owner: 'RENTING',
        currentOdometer: 22000,
        active: true,
        activeFrom: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    vehicleExtras: [
      {
        id: 'extra-1',
        code: 'SEGURO_BASICO',
        name: 'Seguro Básico',
        pricingMode: 'PER_DAY',
        unitPrice: 8,
        active: true,
        createdAt: NOW,
      },
      {
        id: 'extra-2',
        code: 'CDW',
        name: 'CDW (Colisión sin franquicia)',
        pricingMode: 'PER_DAY',
        unitPrice: 15,
        active: true,
        createdAt: NOW,
      },
    ],
    vehicleInsurances: [],
    vehicleTasks: [],
    reservations: [
      {
        id: 'rsv-1', number: rsv(1), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-1', categoryId: 'cat-mini', assignedPlate: '1234ABC',
        startDate: d(-3), startTime: '09:00', endDate: d(2), endTime: '18:00',
        billedDays: 6, basePrice: 180, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 180,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-2', number: rsv(2), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Aeropuerto',
        clientId: 'client-2', categoryId: 'cat-mini', assignedPlate: '1234ABC',
        startDate: d(4), startTime: '10:00', endDate: d(8), endTime: '17:00',
        billedDays: 5, basePrice: 150, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 150,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-3', number: rsv(3), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-1', categoryId: 'cat-compacto', assignedPlate: '5678DEF',
        startDate: d(-1), startTime: '09:00', endDate: d(5), endTime: '18:00',
        billedDays: 7, basePrice: 280, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 280,
        extras: [],
        status: 'CONFIRMADA' as const, contractId: 'ctr-1', notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-4', number: rsv(4), branchId: 'branch-1',
        pickupLocation: 'Puerto', returnLocation: 'Puerto',
        clientId: 'client-2', categoryId: 'cat-compacto', assignedPlate: '5678DEF',
        startDate: d(6), startTime: '08:00', endDate: d(11), endTime: '18:00',
        billedDays: 6, basePrice: 240, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 240,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-5', number: rsv(5), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Aeropuerto',
        clientId: 'client-2', categoryId: 'cat-suv', assignedPlate: '9012GHI',
        startDate: d(3), startTime: '09:00', endDate: d(9), endTime: '17:00',
        billedDays: 7, basePrice: 406, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 406,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-6', number: rsv(6), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Oficina Principal',
        clientId: 'client-1', categoryId: 'cat-suv', assignedPlate: '9012GHI',
        startDate: d(15), startTime: '10:00', endDate: d(19), endTime: '18:00',
        billedDays: 5, basePrice: 290, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 290,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-7', number: rsv(7), branchId: 'branch-1',
        pickupLocation: 'Oficina Principal', returnLocation: 'Oficina Principal',
        clientId: 'client-2', categoryId: 'cat-compacto',
        startDate: d(2), startTime: '09:00', endDate: d(7), endTime: '18:00',
        billedDays: 6, basePrice: 240, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 240,
        extras: [],
        status: 'PETICION' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
      {
        id: 'rsv-8', number: rsv(8), branchId: 'branch-1',
        pickupLocation: 'Aeropuerto', returnLocation: 'Aeropuerto',
        clientId: 'client-1', categoryId: 'cat-mini',
        startDate: d(10), startTime: '11:00', endDate: d(14), endTime: '17:00',
        billedDays: 5, basePrice: 125, extrasTotal: 0, insuranceTotal: 0,
        fuelCharge: 0, penalties: 0, discount: 0, total: 125,
        extras: [],
        status: 'CONFIRMADA' as const, notes: '', auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
    ],
    contracts: [
      {
        id: 'ctr-1',
        number: 'MAD-2026-000001',
        reservationId: 'rsv-3',
        branchId: 'branch-1',
        clientId: 'client-1',
        plate: '5678DEF',
        categoryId: 'cat-compacto',
        pickupLocation: 'Oficina Principal',
        returnLocation: 'Oficina Principal',
        startDate: d(-1), startTime: '09:00',
        endDate: d(5), endTime: '18:00',
        billedDays: 7,
        basePrice: 280,
        extrasTotal: 0, insuranceTotal: 0, fuelCharge: 0,
        penalties: 0, discount: 0, total: 280,
        extras: [],
        status: 'ABIERTO' as const,
        payments: [],
        internalExpenseIds: [],
        auditLog: [],
        createdBy: 'user-admin', createdAt: NOW, updatedAt: NOW,
      },
    ],
    invoices: [],
    tariffPlans: [
      {
        id: 'tariff-1',
        name: 'Tarifa Estándar 2026',
        pricingMode: 'PRECIO_A',
        validFrom: '2026-01-01',
        validTo: '2026-12-31',
        active: true,
        createdAt: NOW,
      },
    ],
    tariffBrackets: [
      {
        id: 'bracket-1',
        planId: 'tariff-1',
        label: '1-3 días',
        minDays: 1,
        maxDays: 3,
        order: 1,
      },
      {
        id: 'bracket-2',
        planId: 'tariff-1',
        label: '4-7 días',
        minDays: 4,
        maxDays: 7,
        order: 2,
      },
      {
        id: 'bracket-3',
        planId: 'tariff-1',
        label: '8+ días',
        minDays: 8,
        maxDays: null,
        order: 3,
      },
    ],
    tariffPrices: [
      // bracket-1
      { id: 'tp-1', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-mini', price: 35 },
      { id: 'tp-2', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-compacto', price: 45 },
      { id: 'tp-3', planId: 'tariff-1', bracketId: 'bracket-1', categoryId: 'cat-suv', price: 65 },
      // bracket-2
      { id: 'tp-4', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-mini', price: 30 },
      { id: 'tp-5', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-compacto', price: 40 },
      { id: 'tp-6', planId: 'tariff-1', bracketId: 'bracket-2', categoryId: 'cat-suv', price: 58 },
      // bracket-3
      { id: 'tp-7', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-mini', price: 25 },
      { id: 'tp-8', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-compacto', price: 35 },
      { id: 'tp-9', planId: 'tariff-1', bracketId: 'bracket-3', categoryId: 'cat-suv', price: 50 },
    ],
    expenses: [],
    salesChannels: [
      {
        id: 'channel-1',
        name: 'Directo',
        code: 'DIR',
        commissionPercent: 0,
        active: true,
        createdAt: NOW,
      },
      {
        id: 'channel-2',
        name: 'Online',
        code: 'ONL',
        commissionPercent: 10,
        active: true,
        createdAt: NOW,
      },
    ],
    templates: [],
    vehicleBlocks: [
      {
        id: 'block-1',
        plate: '9012GHI',
        startDate: d(11),
        endDate: d(13),
        reason: 'ITV',
        createdBy: 'user-admin',
        createdAt: NOW,
      },
    ],
  };
}
