export type MacroEntry = { macro: string; description: string };
export type MacroGroup = { key: string; title: string; macros: MacroEntry[] };

export const TEMPLATE_MACRO_GROUPS: MacroGroup[] = [
  {
    key: 'EMPRESA',
    title: 'Empresa',
    macros: [
      { macro: '{company_name}', description: 'Nombre de empresa' },
      { macro: '{company_document_name}', description: 'Nombre en documentos' },
      { macro: '{company_tax_id}', description: 'NIF/CIF' },
      { macro: '{company_fiscal_address}', description: 'Dirección fiscal' },
      { macro: '{company_phone}', description: 'Teléfono' },
      { macro: '{company_email_from}', description: 'Email remitente' },
      { macro: '{company_website}', description: 'Web' },
      { macro: '{company_document_footer}', description: 'Pie de página' },
      { macro: '{company_logo_data_url}', description: 'Logo (base64)' },
      { macro: '{company_brand_primary_color}', description: 'Color primario' },
      { macro: '{company_brand_secondary_color}', description: 'Color secundario' },
    ],
  },
  {
    key: 'CLIENTE',
    title: 'Cliente',
    macros: [
      { macro: '{customer_name}', description: 'Nombre completo del cliente' },
      { macro: '{customer_first_name}', description: 'Nombre' },
      { macro: '{customer_email}', description: 'Email' },
      { macro: '{customer_phone}', description: 'Teléfono' },
      { macro: '{customer_tax_id}', description: 'NIF/DNI/Pasaporte' },
      { macro: '{customer_address}', description: 'Dirección' },
      { macro: '{customer_city}', description: 'Ciudad' },
      { macro: '{customer_province}', description: 'Provincia' },
      { macro: '{customer_country}', description: 'País' },
      { macro: '{customer_postal_code}', description: 'Código postal' },
      { macro: '{customer_driving_license}', description: 'Nº permiso conducir' },
      { macro: '{customer_document_type}', description: 'Tipo documento' },
      { macro: '{customer_document_number}', description: 'Nº documento' },
      { macro: '{customer_nationality}', description: 'Nacionalidad' },
    ],
  },
  {
    key: 'CONFIRMACION_RESERVA',
    title: 'Confirmación de reserva',
    macros: [
      { macro: '{reservation_number}', description: 'Número de reserva' },
      { macro: '{reservation_status}', description: 'Estado de la reserva' },
      { macro: '{delivery_place}', description: 'Lugar de entrega' },
      { macro: '{delivery_date}', description: 'Fecha de entrega' },
      { macro: '{delivery_time}', description: 'Hora de entrega' },
      { macro: '{delivery_flight}', description: 'Vuelo de llegada' },
      { macro: '{pickup_place}', description: 'Lugar de recogida' },
      { macro: '{pickup_date}', description: 'Fecha de recogida' },
      { macro: '{pickup_time}', description: 'Hora de recogida' },
      { macro: '{pickup_flight}', description: 'Vuelo de salida' },
      { macro: '{billed_car_group}', description: 'Grupo facturado' },
      { macro: '{assigned_plate}', description: 'Matrícula asignada' },
      { macro: '{billed_days}', description: 'Días facturados' },
      { macro: '{applied_rate}', description: 'Tarifa aplicada' },
      { macro: '{base_amount}', description: 'Importe base' },
      { macro: '{extras_amount}', description: 'Importe extras' },
      { macro: '{insurance_amount}', description: 'Importe seguro' },
      { macro: '{fuel_amount}', description: 'Combustible' },
      { macro: '{discount_amount}', description: 'Descuento' },
      { macro: '{total_price}', description: 'Total' },
      { macro: '{extras_breakdown}', description: 'Desglose de extras' },
      { macro: '{deductible}', description: 'Franquicia' },
      { macro: '{deposit_amount}', description: 'Depósito' },
      { macro: '{public_observations}', description: 'Observaciones' },
      { macro: '{payments_made}', description: 'Pagos realizados' },
      { macro: '{iva_percent}', description: 'IVA (%)' },
    ],
  },
  {
    key: 'PRESUPUESTO',
    title: 'Presupuesto',
    macros: [
      { macro: '{delivery_place}', description: 'Lugar de entrega' },
      { macro: '{delivery_date}', description: 'Fecha de entrega' },
      { macro: '{delivery_time}', description: 'Hora de entrega' },
      { macro: '{pickup_place}', description: 'Lugar de recogida' },
      { macro: '{pickup_date}', description: 'Fecha de recogida' },
      { macro: '{pickup_time}', description: 'Hora de recogida' },
      { macro: '{billed_car_group}', description: 'Grupo facturado' },
      { macro: '{billed_days}', description: 'Días' },
      { macro: '{applied_rate}', description: 'Tarifa' },
      { macro: '{base_amount}', description: 'Base' },
      { macro: '{discount_amount}', description: 'Descuento' },
      { macro: '{insurance_amount}', description: 'Seguro' },
      { macro: '{extras_amount}', description: 'Extras' },
      { macro: '{fuel_amount}', description: 'Combustible' },
      { macro: '{total_amount}', description: 'Total' },
      { macro: '{extras_breakdown}', description: 'Desglose extras' },
    ],
  },
  {
    key: 'FACTURA',
    title: 'Factura',
    macros: [
      { macro: '{invoice_number}', description: 'Número de factura' },
      { macro: '{issued_at}', description: 'Fecha de emisión' },
      { macro: '{contract_number}', description: 'Nº contrato asociado' },
      { macro: '{customer_name}', description: 'Cliente' },
      { macro: '{customer_tax_id}', description: 'NIF/DNI cliente' },
      { macro: '{customer_address}', description: 'Dirección cliente' },
      { macro: '{customer_email}', description: 'Email cliente' },
      { macro: '{driver_name}', description: 'Conductor' },
      { macro: '{billed_car_group}', description: 'Grupo facturado' },
      { macro: '{applied_rate}', description: 'Tarifa' },
      { macro: '{rental_period_detail}', description: 'Periodo de alquiler' },
      { macro: '{vehicle_detail}', description: 'Detalle vehículo' },
      { macro: '{vehicle_occupation_amount}', description: 'Ocupación vehículo' },
      { macro: '{base_amount}', description: 'Base imponible' },
      { macro: '{discount_amount}', description: 'Descuento' },
      { macro: '{extras_amount}', description: 'Extras' },
      { macro: '{fuel_amount}', description: 'Combustible' },
      { macro: '{insurance_amount}', description: 'Seguro' },
      { macro: '{penalties_amount}', description: 'Penalizaciones' },
      { macro: '{iva_percent}', description: 'IVA (%)' },
      { macro: '{iva_amount}', description: 'Importe IVA' },
      { macro: '{total_amount}', description: 'Total factura' },
    ],
  },
  {
    key: 'CONTRATO',
    title: 'Contrato',
    macros: [
      { macro: '{contract_number}', description: 'Número de contrato' },
      { macro: '{contract_status}', description: 'Estado del contrato' },
      { macro: '{contract_date}', description: 'Fecha del contrato' },
      { macro: '{customer_name}', description: 'Cliente' },
      { macro: '{customer_tax_id}', description: 'NIF/DNI' },
      { macro: '{customer_address}', description: 'Dirección' },
      { macro: '{customer_phone}', description: 'Teléfono' },
      { macro: '{customer_email}', description: 'Email' },
      { macro: '{customer_driving_license}', description: 'Permiso conducir' },
      { macro: '{assigned_plate}', description: 'Matrícula' },
      { macro: '{vehicle_model}', description: 'Modelo vehículo' },
      { macro: '{vehicle_category}', description: 'Categoría' },
      { macro: '{km_out}', description: 'Km salida' },
      { macro: '{km_in}', description: 'Km llegada' },
      { macro: '{fuel_out}', description: 'Combustible salida' },
      { macro: '{fuel_in}', description: 'Combustible llegada' },
      { macro: '{delivery_place}', description: 'Lugar entrega' },
      { macro: '{delivery_date}', description: 'Fecha entrega' },
      { macro: '{delivery_time}', description: 'Hora entrega' },
      { macro: '{pickup_place}', description: 'Lugar recogida' },
      { macro: '{pickup_date}', description: 'Fecha recogida' },
      { macro: '{pickup_time}', description: 'Hora recogida' },
      { macro: '{billed_days}', description: 'Días facturados' },
      { macro: '{base_amount}', description: 'Base' },
      { macro: '{total_amount}', description: 'Total' },
      { macro: '{deposit_amount}', description: 'Depósito' },
      { macro: '{deductible}', description: 'Franquicia' },
      { macro: '{payment_method}', description: 'Método de pago' },
      { macro: '{applied_rate}', description: 'Tarifa' },
    ],
  },
];
